### ISSUE TITLE
Dont start

### ISSUE THREAD

**Issue by pomazanbohdan** [ruudud/devdns#17]
1. i add 
      - FALLBACK_DNS=1.1.1.1
2. dc pull
3. dc up -d

Cycle restart:
![image](https://user-images.githubusercontent.com/696713/81494878-c7ad1880-92b4-11ea-9b8d-8058ba4da979.png)

**Comment by pomazanbohdan** [comment]
`# FALLBACK_DNS=1.1.1.1`

![image](https://user-images.githubusercontent.com/696713/81494896-ed3a2200-92b4-11ea-9460-240e5f048122.png)

**Comment by ruudud** [comment]
how do you run it? the full `docker run`

**Comment by pomazanbohdan** [comment]
```
version: '3'

services:
  dns:
    image: ruudud/devdns
    hostname: dns
    container_name: dns
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    ports:
      - "127.0.0.1:53:53/udp"
    environment:
      - DNS_DOMAIN=pomazan
      - NETWORK=auto
#      - FALLBACK_DNS=1.1.1.1
    labels:
      - "traefik.enable=false"
```
docker-composer down
docker-composer pull 
docker-composer up -d

**Comment by pomazanbohdan** [comment]
i stop end delete container, start again,

```
dcupd
Pulling dns (ruudud/devdns:)...
latest: Pulling from ruudud/devdns
31603596830f: Pull complete
707211e0a0e2: Pull complete
ce4d3476ccaf: Pull complete
43bc1c036716: Pull complete
8d15b6839874: Pull complete
Digest: sha256:66c02ad2c63afd70a51767504bb269ffbc79f13512b5862023845a194fa84237
Status: Downloaded newer image for ruudud/devdns:latest
Creating dns ... done
```

error start

(dcupd alias to docker-composer up -d)

**Comment by pomazanbohdan** [comment]
@ruudud 
Please roll back temporarily changes in the master branch to return the docker working build to a working fix.

**Comment by ruudud** [comment]
I would if I could reproduce this myself. 

What is your docker version? Are you able to start other containers without any problems?

**Comment by pomazanbohdan** [comment]
Docker version 19.03.8, build afacb8b

Yes, everything starts.

**Comment by ruudud** [comment]
Could you also try running without docker compose in the mix?

eg. `docker run -d --name dns --network=host -e FALLBACK_DNS=1.1.1.1 -e DNS_DOMAIN=pomazan -e NETWORK=auto -p 53:53/udp -v /var/run/docker.sock:/var/run/docker.sock ruudud/devdns`

Just to be clear, the only problem you're observering is restarts? And nothing in the log?

**Comment by ruudud** [comment]
Oh, and also include `-e DEBUG=1` to get more output

**Comment by pomazanbohdan** [comment]
53 use (((
need add check port use or not

**Comment by pomazanbohdan** [comment]
`
udp        0      0 127.0.0.53:53           0.0.0.0:*                           1439/systemd-resolv
udp        0      0 0.0.0.0:5355            0.0.0.0:*                           1439/systemd-resolv
`

I apologize)
I just don’t understand why the system launched its service.

I will watch and edit.

**Comment by ruudud** [comment]
No worries. Strange you didn't see any error from docker compose..

**Comment by pomazanbohdan** [comment]
No no.
This docker composer works, it’s simple for the host, for some reason the systemd-resolved service started.

**Comment by pomazanbohdan** [comment]
i stop local service **systemd-resolved** and run not host

```
version: '3'

services:
  dns:
    image: ruudud/devdns
    hostname: dns
    container_name: dns
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
#    network_mode: host
    ports:
      - "127.0.0.1:53:53/udp"
    environment:
      - DNS_DOMAIN=pomazan
      - NETWORK=auto
      - FALLBACK_DNS=1.1.1.1
    labels:
      - "traefik.enable=false"

```

Work.
