### ISSUE TITLE
 dnsmasq: failed to create listening socket for port 53: Address in use

### ISSUE THREAD

**Issue by pomazanbohdan** [ruudud/devdns#19]
Centos

1.
```
sudo netstat -pna | grep 53
udp        0      0 127.0.0.53:53           0.0.0.0:*                           877/systemd-resolve
```

2.
```
  dns:
    image: ruudud/devdns
    hostname: dns
    container_name: dns
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc/resolv.conf:/mnt/resolv.conf
    network_mode: bridge
    environment:
      - DNS_DOMAIN=pomazan
      - NETWORK=auto
      - FALLBACK_DNS=1.1.1.1
      - HOSTMACHINE_IP=172.17.0.2
    labels:
      - "traefik.enable=false"
```

```
nameserver 172.17.0.2 # added by devdns
# Generated by NetworkManager
search pomazan.xyz
nameserver 1.1.1.1
nameserver 8.8.8.8
```

This error will appear when a new container starts:

![image](https://user-images.githubusercontent.com/696713/107018523-374f2600-67a9-11eb-8fe8-a7a28eb6d0b2.png)

```

+ Replaced misto-php-apache-platforma.pomazan → 172.18.0.28
dnsmasq: failed to create listening socket for port 53: Address in use
/run.sh: line 28: kill: (1012) - No such process,

```
